data_folder: /scratch/talks/data/cryoetsim_data/combined_clean_inverted_scaled
patches_folder: /scratch/talks/cryosiam_experiments/dense_simsiam_pretraining/patches_0
logging:
  logger: "wandb"
  project: "dense_simsiam_pre-training"
  name: model1
  log_dir: /g/kreshuk/talks/cryosiam_results/dense_simsiam_pretraining/model1
file_extension: '.mrc'

train_files: null

val_files: null
validation_ratio: 0.5
noisy_data_folder: null
noisy_patches_folder: null

continue_training: False

parameters:
  nodes: 1
  gpu_devices: 1
  data:
    patch_size: [ 128, 128, 128 ]
    patch_overlap: 0.5
    view_size: [64, 64, 64]
    view_overlap: 0.5
    min: 0
    max: 1
    mean: 0
    std:  1
  transforms:
    low_pass_sigma_range: [0.5, 2]
    high_pass_sigma_range: [0.1, 0.5]
    high_pass_sigma2_range: [1,5]
    noise_sigma_range: [0.1, 0.5]
    combine_transforms: True
    drop_out_prob: 0.5
    drop_out: 0.5
    use_noisy_input: False
  network:
    block_type: 'basic'
    spatial_dims: 3
    in_channels: 1
    num_layers: [1,1,1,1]
    num_filters: [64, 128, 256, 512]
    fpn_channels: 128
    no_max_pool: True
    dim: 256
    pred_dim: 64
    dense_dim: 64
    dense_pred_dim: 16
    include_levels_loss: True
    add_fpn_later_conv: False
    decoder_type: "fpn"
    fpn_layers: 2
    include_global_loss: True
    weight_dense_loss: null

hyper_parameters:
  batch_size: 10
  lr: 0.5
  momentum: 0.9
  weight_decay: 0.00001
  fix_pred_lr: False
  max_epochs: 200
  lr_warmup_epochs: 5
  val_interval: 10
  cache_rate: 0
  replace_rate: null
